name: fluidnodes-vps

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */5 * * *"

jobs:
  ubuntu_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash
          mkdir -p ~/.config/rclone
          echo "[terabox]
type = webdav
url = https://dav.terabox.com/dav
vendor = other
user = ${{ secrets.TERABOX_USER }}
pass = ${{ secrets.TERABOX_PASS }}" > ~/.config/rclone/rclone.conf

      - name: Restore Data from TeraBox
        run: |
          mkdir -p data
          rclone copy terabox:/fluidnodes-backup ./data --progress || echo "No backup found"

      - name: Start VPS (SSH)
        run: |
          curl -sSf https://sshx.io/get | sh -s run
          echo "VPS ready, data restored in ./data"

      - name: Auto Backup Loop
        run: |
          nohup bash -c '
          while true; do
            rclone sync ./data terabox:/fluidnodes-backup --progress
            sleep 900
          done
          ' > backup.log 2>&1 &
