name: fluidnodes-vps

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */5 * * *" # Runs every 5 hours to restart before GitHub limit

jobs:
  ubuntu_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash
          mkdir -p ~/.config/rclone
          cat <<EOF > ~/.config/rclone/rclone.conf
          [terabox]
          type = webdav
          url = https://dav.terabox.com/dav
          vendor = other
          user = ${TERABOX_USER}
          pass = ${TERABOX_PASS}
          EOF
        env:
          TERABOX_USER: ${{ secrets.TERABOX_USER }}
          TERABOX_PASS: ${{ secrets.TERABOX_PASS }}

      - name: Restore Data from TeraBox
        run: |
          mkdir -p data
          rclone copy terabox:/fluidnodes-backup ./data --progress || echo "No backup found"

      - name: Start VPS (SSH)
        run: |
          curl -sSf https://sshx.io/get | sh -s run
          echo "VPS ready, data restored in ./data"

      - name: Auto Backup Loop
        run: |
          while true; do
            rclone sync ./data terabox:/fluidnodes-backup --progress
            sleep 900
          done &
